function actionHelper() {
  const ACTIONS = {
    LOGIN: "LOGIN",
    LOGOUT: "END_LOADING",
    START_LOADING: "START_LOADING",
    END_LOADING: "END_LOADING",
    OPEN_LOGIN: "OPEN_LOGIN",
    CLOSE_LOGIN: "CLOSE_LOGIN",
    OPEN_USER: "OPEN_USER",
    CLOSE_USER: "CLOSE_USER",
    OPEN_PROJECT: "OPEN_PROJECT",
    CLOSE_PROJECT: "CLOSE_PROJECT",
    OPEN_INFRASTRUCTURE: "OPEN_INFRASTRUCTURE",
    CLOSE_INFRASTRUCTURE: "CLOSE_INFRASTRUCTURE",
    OPEN_ROAD: "OPEN_ROAD",
    CLOSE_ROAD: "CLOSE_ROAD",
    UPDATE_ALERT: "UPDATE_ALERT",
    UPDATE_USER: "UPDATE_USER",
    UPDATE_USER_PROFILE: "UPDATE_USER_PROFILE",
    RESET_USER_PROFILE: "RESET_USER_PROFILE",
    UPDATE_PROJECT: "UPDATE_PROJECT",
    RESET_PROJECT: "RESET_PROJECT",
    UPDATE_INFRASTRUCTURE: "UPDATE_INFRASTRUCTURE",
    RESET_INFRASTRUCTURE: "RESET_INFRASTRUCTURE",
    UPDATE_ROAD: "UPDATE_ROAD",
    RESET_ROAD: "RESET_ROAD",

    OPEN_TASK: "OPEN_TASK",
    CLOSE_TASK: "CLOSE_TASK",
    UPDATE_TASK: "UPDATE_TASK",
    RESET_TASK: "RESET_TASK",
  };

  return ACTIONS;
}

export default actionHelper;
