export const roadsData = [
  {
    id: 1,
    roadId: 1,
    provincialRoad: "Somaaaoge",
    roadlocation: "Catarman N. Samar",
    roadLength: 3.954,
    remarks: "Updated",
  },
  {
    id: 2,
    roadId: 2,
    provincialRoad: "Somoge",
    roadlocation: "Catarman N. Samar",
    roadLength: 3.954,
    remarks: "Updated",
  },
  {
    id: 3,
    roadId: 3,
    provincialRoad: "Somoge",
    roadlocation: "Catarman N. Samar",
    roadLength: 3.954,
    remarks: "Updated",
  },
];

export const progressReportData = [
  {
    id: 1,
    name_of_project: "Construction/ Rehabilitation of Polangi-Liberty FMR",
    contractId: "NS-02-19-20-03",
    location: "Catarman, Northern Samar",
    contractor: "SOLID M Construction",
    contract_amount: "48,783,386,45",
    contract_amount_revised: "48,783,386,45",
    previous_percent_accomplishment: "45%",
    current_percent_accomplishment: "70%",
    slippage: "0.00%",
    target_completion_date: "December 8, 2022",
    target_completion_date_revised: "March 10, 2023",
    project_engineer: "Jennifer M. Evangelista",
    remarks:
      "Ongoing with Time Suspension due to unworkable field conditions caused by heavy rains within the project site",
  },
  {
    id: 2,
    name_of_project: "Construction/ Rehabilitation of Polangi-Liberty FMR",
    contractId: "NS-02-19-20-03",
    location: "Catarman, Northern Samar",
    contractor: "SOLID M Construction",
    contract_amount: "48,783,386,45",
    contract_amount_revised: "48,783,386,45",
    previous_percent_accomplishment: "45%",
    current_percent_accomplishment: "70%",
    slippage: "0.00%",
    target_completion_date: "December 8, 2022",
    target_completion_date_revised: "March 10, 2023",
    project_engineer: "Jennifer M. Evangelista",
    remarks: "Ongoing w",
  },
  {
    id: 3,
    name_of_project: "Construction/ Rehabilitation of Polangi-Liberty FMR",
    contractId: "NS-02-19-20-03",
    location: "Catarman, Northern Samar",
    contractor: "SOLID M Construction",
    contract_amount: "48,783,386,45",
    contract_amount_revised: "48,783,386,45",
    previous_percent_accomplishment: "45%",
    current_percent_accomplishment: "70%",
    slippage: "0.00%",
    target_completion_date: "December 8, 2022",
    target_completion_date_revised: "March 10, 2023",
    project_engineer: "Jennifer M. Evangelista",
    remarks: "Completed",
  },
];
